/-
Copyright (c) 2026 Tetsuo Yokoyama. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Tetsuo Yokoyama
-/
import CslibReversible.Diamond
import CslibReversible.Parabolic
import CslibReversible.CausalConsistency
import Mathlib.Logic.Function.Basic

/-!
# Sequential reversible languages: backward determinism is the whole story

The instances built so far — `Instances.Product` and `Instances.CCSK` — are
concurrent, and their work goes into an independence relation with content.
A *sequential* reversible language has no concurrency to speak of, and the
axioms collapse: take independence to be the **empty** relation and every
axiom of the theory becomes either trivial or vacuous, except one.  The
survivor is `BTI`, which over the empty relation says exactly

> distinct coinitial backward transitions do not exist,

that is, **backward determinism**.  So a sequential reversible language
inherits the whole theory by discharging a single property, and it is the one
property such a language has always already proved: R-CORE, R-WHILE, Janus,
RFUN and reversible C all establish backward determinism (usually as one half
of "the semantics is a partial injection") before anything else.  This file
turns that one lemma into `parabolic`, `causal_consistency`, `unique_origin`,
`exists_origin` and `bstep_diamond`.

What causal equivalence *means* here is worth stating: with no independent
pairs, `CEq` is generated by cancellation alone, so causal consistency reads
"two computations between the same two states differ only by inserted
undo/redo pairs".  For a deterministic sequential machine that is the sharpest
true statement, and it is not trivial — the paths may still be different lists.

`WellFoundedBwd` and `BStepDec` are *not* discharged generically: whether
undoing terminates, and whether the previous step can be computed, depend on
the language.  They are required as hypotheses instead.

## Main definitions

- `NoIndep`: the empty independence relation.
- `BwdDeterministic`: two valid coinitial backward transitions are equal.
- `RevAssign`: a small sequential reversible language, present so that the
  above is not an empty exercise.

## Main statements

- `BwdDeterministic` gives `BTI lts NoIndep`, and (with decidable equality)
  conversely: over the empty relation the two are the same statement.
- `parabolic_of_bwdDeterministic`, `bstep_diamond_of_bwdDeterministic`,
  `causal_consistency_of_bwdDeterministic`, `unique_origin_of_bwdDeterministic`,
  `exists_origin_of_bwdDeterministic`: the inherited theory.
- `RevAssign.bwdDeterministic`, and hence
  `RevAssign.causal_consistency_revAssign` and
  `RevAssign.unique_origin_revAssign`.

## References

* [I. Lanese, I. Phillips, I. Ulidowski, *An Axiomatic Theory for Reversible
  Computation*, ACM TOCL 25(2), 2024][LPU2024]
* [T. Yokoyama, H.B. Axelsen, R. Glück, *Principles of a reversible
  programming language*, CF 2008][YokoyamaAxelsenGlück2008]
-/

universe u v

namespace Cslib.LTS

variable {State : Type u} {Label : Type v}

/-! ## The empty independence relation -/

/--
The empty independence relation: nothing is independent of anything.

This is the right choice for a sequential language, where there is no
concurrency for independence to record.
-/
def NoIndep (_t _u : Transition State Label) : Prop := False

@[simp] theorem noIndep_iff {t u : Transition State Label} :
    NoIndep t u ↔ False := Iff.rfl

/-- Vacuously, the empty relation relates only coinitial transitions. -/
instance instIsIndepNoIndep (lts : LTS State Label) :
    IsIndep lts (NoIndep (State := State) (Label := Label)) where
  coinitial h := False.elim h

/-- Vacuously, the empty relation is symmetric. -/
instance instIndepSymmNoIndep :
    IndepSymm (NoIndep (State := State) (Label := Label)) where
  symm h := False.elim h

/-- Vacuously, the empty relation is generated by labels. -/
instance instCLGNoIndep : CLG (NoIndep (State := State) (Label := Label)) where
  clg h _ _ _ := False.elim h

/--
**The Square Property, vacuously.**  There is no independent pair to close a
square on.
-/
instance instSquarePropertyNoIndep (lts : LTS State Label) :
    SquareProperty lts (NoIndep (State := State) (Label := Label)) where
  square _ _ h := False.elim h

/-! ## Backward determinism -/

/--
**Backward determinism.**  A valid backward transition is determined by the
state it leaves.

This is the property every sequential reversible language proves: it is one
half of "the semantics is a partial injective function", the other half being
forward determinism, which the theory does not need.

Note what is being asserted.  Equality of `Transition` is equality of source,
label, direction *and* target, so backward determinism here says that from a
given state there is at most one way to step back — the same label and the
same predecessor.
-/
class BwdDeterministic (lts : LTS State Label) : Prop where
  /-- Two valid coinitial backward transitions are equal. -/
  bwd_unique : ∀ {t u : Transition State Label}, t.Valid lts → t.IsBwd →
    u.Valid lts → u.IsBwd → t.Coinitial u → t = u

/--
**BTI over the empty relation is backward determinism.**

BTI asks that distinct coinitial backward transitions be independent; with
nothing independent, it asks that there be no distinct coinitial backward
transitions at all.
-/
instance instBTINoIndep (lts : LTS State Label) [BwdDeterministic lts] :
    BTI lts (NoIndep (State := State) (Label := Label)) where
  bti htv huv hco htb hub hne :=
    absurd (BwdDeterministic.bwd_unique htv htb huv hub hco) hne

/--
The converse: if the empty relation satisfies BTI then the LTS is backward
deterministic.  So over `NoIndep` the two notions coincide, and `BTI` is the
*only* axiom with content in the sequential case.

Decidable equality is used to keep the proof constructive; classically the
hypothesis `[DecidableEq _]` is unnecessary.
-/
theorem bwdDeterministic_of_bti [DecidableEq State] [DecidableEq Label]
    (lts : LTS State Label) [BTI lts (NoIndep (State := State) (Label := Label))] :
    BwdDeterministic lts where
  bwd_unique htv htb huv hub hco :=
    Decidable.byContradiction fun hne =>
      BTI.bti (Indep := NoIndep) htv huv hco htb hub hne

/-! ## What a backward deterministic LTS inherits -/

section Inherited

/--
**The Parabolic Lemma.**  Every computation of a backward deterministic LTS is
causally equivalent to one that undoes and then redoes.
-/
theorem parabolic_of_bwdDeterministic [DecidableEq State] [DecidableEq Label]
    {lts : LTS State Label} [BwdDeterministic lts]
    {l : List (Transition State Label)} {p q : State} (hc : Chained lts p l q) :
    ∃ lb lf, (∀ x ∈ lb, x.IsBwd) ∧ (∀ x ∈ lf, x.IsFwd) ∧
      CEq lts (NoIndep (State := State) (Label := Label)) p q l (lb ++ lf) :=
  parabolic (Indep := NoIndep) hc

/--
**Undoing is confluent.**  Trivially so here: backward determinism says the
two backward steps were the same step.
-/
theorem bstep_diamond_of_bwdDeterministic [DecidableEq State] [DecidableEq Label]
    {lts : LTS State Label} [BwdDeterministic lts] {p q₁ q₂ : State}
    (h₁ : BStep lts p q₁) (h₂ : BStep lts p q₂) :
    q₁ = q₂ ∨ ∃ w, BStep lts q₁ w ∧ BStep lts q₂ w :=
  bstep_diamond (Indep := NoIndep) h₁ h₂

/--
**Causal consistency.**  Two computations of a backward deterministic LTS with
the same endpoints are causally equivalent — over the empty independence
relation, they differ only by inserted undo/redo pairs.
-/
theorem causal_consistency_of_bwdDeterministic [DecidableEq State] [DecidableEq Label]
    {lts : LTS State Label} [BwdDeterministic lts] [WellFoundedBwd lts] [BStepDec lts]
    {p q : State} {l₁ l₂ : List (Transition State Label)}
    (h₁ : Chained lts p l₁ q) (h₂ : Chained lts p l₂ q) :
    CEq lts (NoIndep (State := State) (Label := Label)) p q l₁ l₂ :=
  causal_consistency (Indep := NoIndep) h₁ h₂

/-- **However a state is rewound, the origin reached is the same.** -/
theorem unique_origin_of_bwdDeterministic [DecidableEq State] [DecidableEq Label]
    {lts : LTS State Label} [BwdDeterministic lts] [WellFoundedBwd lts] [BStepDec lts]
    {p o₁ o₂ : State}
    (h₁ : Relation.ReflTransGen (BStep lts) p o₁) (ho₁ : Origin lts o₁)
    (h₂ : Relation.ReflTransGen (BStep lts) p o₂) (ho₂ : Origin lts o₂) :
    o₁ = o₂ :=
  unique_origin (Indep := NoIndep) h₁ ho₁ h₂ ho₂

/-- Every state can be rewound to a state with nothing left to undo. -/
theorem exists_origin_of_bwdDeterministic {lts : LTS State Label}
    [WellFoundedBwd lts] [BStepDec lts] (p : State) :
    ∃ o, Relation.ReflTransGen (BStep lts) p o ∧ Origin lts o :=
  exists_origin p

end Inherited

end Cslib.LTS

/-!
# A witness: reversible assignment sequences

Nothing above says that a backward deterministic LTS exists, so here is one:
a machine executing a straight-line sequence of reversible assignments
`r += e`, with the usual side condition that `e` does not read `r`.  This is
the fragment every reversible imperative language is built on — Janus's
`x += e`, R-CORE's reversible update — reduced to the point where the reason
backward determinism holds is visible: the side condition makes `env ↦ env[r ↦
env r + e]` injective, with `env ↦ env[r ↦ env r - e]` as its inverse.
-/

namespace Cslib.LTS.RevAssign

variable {n : Nat}

/-- A store: the contents of the `n` registers. -/
abbrev Env (n : Nat) := Fin n → Int

/--
Stores have decidable equality: check the registers one by one.

Mathlib's instance for functions out of a `Fintype` proves the same thing but
pulls in `Classical.choice`, which the rest of this development does without;
compare the note on `reflTransGen_cases_head`.  It is `scoped` so that it does
not displace mathlib's instance outside this file.
-/
scoped instance instDecidableEqEnv : DecidableEq (Env n) := fun f g =>
  decidable_of_iff (∀ i, f i = g i) ⟨funext, fun h _ => h ▸ rfl⟩

/-- Integer expressions over the registers. -/
inductive Expr (n : Nat) where
  /-- A constant. -/
  | const (k : Int) : Expr n
  /-- The current contents of a register. -/
  | var (r : Fin n) : Expr n
  /-- Sum. -/
  | add (e₁ e₂ : Expr n) : Expr n
  /-- Product. -/
  | mul (e₁ e₂ : Expr n) : Expr n
  /-- Negation. -/
  | neg (e : Expr n) : Expr n
  deriving DecidableEq, Repr

/-- The value of an expression in a store. -/
def Expr.eval : Expr n → Env n → Int
  | .const k, _ => k
  | .var r, env => env r
  | .add e₁ e₂, env => e₁.eval env + e₂.eval env
  | .mul e₁ e₂, env => e₁.eval env * e₂.eval env
  | .neg e, env => -e.eval env

/-- `e.Avoids r`: the expression `e` does not read the register `r`. -/
def Expr.Avoids (r : Fin n) : Expr n → Prop
  | .const _ => True
  | .var s => s ≠ r
  | .add e₁ e₂ => e₁.Avoids r ∧ e₂.Avoids r
  | .mul e₁ e₂ => e₁.Avoids r ∧ e₂.Avoids r
  | .neg e => e.Avoids r

/--
An expression that does not read `r` cannot tell that `r` has changed.

This is the semantic content of the side condition, and everything else rests
on it.
-/
theorem Expr.eval_update_of_avoids {r : Fin n} (env : Env n) (v : Int) :
    ∀ e : Expr n, e.Avoids r → e.eval (Function.update env r v) = e.eval env := by
  intro e
  induction e with
  | const k => intro _; rfl
  | var s => intro h; exact Function.update_of_ne h v env
  | add e₁ e₂ ih₁ ih₂ => intro h; simp only [Expr.eval, ih₁ h.1, ih₂ h.2]
  | mul e₁ e₂ ih₁ ih₂ => intro h; simp only [Expr.eval, ih₁ h.1, ih₂ h.2]
  | neg e ih => intro h; simp only [Expr.eval, ih h]

/--
A reversible assignment `reg += expr`, carrying the side condition that makes
it reversible.

Keeping the proof inside the instruction means every program is well formed by
construction, so the instances below need no hypothesis about the program.
-/
structure Instr (n : Nat) where
  /-- The register being updated. -/
  reg : Fin n
  /-- The amount added to it. -/
  expr : Expr n
  /-- The expression may not read the register it updates. -/
  avoids : expr.Avoids reg

/-- Executing an instruction: `reg += expr`. -/
def Instr.run (ins : Instr n) (env : Env n) : Env n :=
  Function.update env ins.reg (env ins.reg + ins.expr.eval env)

/-- Undoing an instruction: `reg -= expr`. -/
def Instr.undo (ins : Instr n) (env : Env n) : Env n :=
  Function.update env ins.reg (env ins.reg - ins.expr.eval env)

/-- Undoing an instruction undoes it. -/
theorem Instr.undo_run (ins : Instr n) (env : Env n) : ins.undo (ins.run env) = env := by
  have hev : ins.expr.eval (ins.run env) = ins.expr.eval env :=
    Expr.eval_update_of_avoids env _ ins.expr ins.avoids
  funext s
  by_cases hs : s = ins.reg
  · subst hs
    rw [Instr.undo, Function.update_self, hev, Instr.run, Function.update_self,
      Int.add_sub_cancel]
  · rw [Instr.undo, Function.update_of_ne hs, Instr.run, Function.update_of_ne hs]

/-- Redoing an undone instruction restores the store. -/
theorem Instr.run_undo (ins : Instr n) (env : Env n) : ins.run (ins.undo env) = env := by
  have hev : ins.expr.eval (ins.undo env) = ins.expr.eval env :=
    Expr.eval_update_of_avoids env _ ins.expr ins.avoids
  funext s
  by_cases hs : s = ins.reg
  · subst hs
    rw [Instr.run, Function.update_self, hev, Instr.undo, Function.update_self,
      Int.sub_add_cancel]
  · rw [Instr.run, Function.update_of_ne hs, Instr.undo, Function.update_of_ne hs]

/--
**The update is injective.**  This is where the side condition earns its keep;
without it `r += r` would map every store to a doubled one and forget the
sign.
-/
theorem Instr.run_injective (ins : Instr n) {env₁ env₂ : Env n}
    (h : ins.run env₁ = ins.run env₂) : env₁ = env₂ := by
  rw [← ins.undo_run env₁, ← ins.undo_run env₂, h]

/-- A program: a finite straight-line sequence of reversible assignments. -/
abbrev Prog (n : Nat) := List (Instr n)

/-- A configuration: the program counter and the store. -/
abbrev Config (n : Nat) := Nat × Env n

/--
The forward semantics: run the instruction the counter points at, and advance.

The label of a step is the index of the instruction executed — the only thing
an observer of a sequential machine can see.
-/
inductive Step (prog : Prog n) : Config n → Nat → Config n → Prop where
  /-- Execute the instruction at the counter. -/
  | assign {i : Nat} {ins : Instr n} (h : prog[i]? = some ins) (env : Env n) :
      Step prog (i, env) i (i + 1, ins.run env)

/-- The machine as an `LTS`. -/
def lts (prog : Prog n) : LTS (Config n) Nat := ⟨Step prog⟩

@[simp] theorem lts_Tr {prog : Prog n} {p q : Config n} {l : Nat} :
    (lts prog).Tr p l q ↔ Step prog p l q := Iff.rfl

/-- Everything a step tells us: which instruction ran, and what it did. -/
theorem step_inv {prog : Prog n} {p q : Config n} {l : Nat} (h : Step prog p l q) :
    ∃ ins, prog[l]? = some ins ∧ p.1 = l ∧ q.1 = l + 1 ∧ q.2 = ins.run p.2 := by
  cases h with
  | assign hi env => exact ⟨_, hi, rfl, rfl, rfl⟩

/--
**Backward determinism.**  The counter of the state reached says which
instruction ran, and the instruction is injective on stores, so the previous
configuration is determined.
-/
instance bwdDeterministic (prog : Prog n) : BwdDeterministic (lts prog) where
  bwd_unique {t u} htv htb huv hub hco := by
    rw [Transition.Valid, htb] at htv
    rw [Transition.Valid, hub] at huv
    have hs : t.src = u.src := hco
    obtain ⟨ins, hins, htgt, hsrc, henv⟩ := step_inv htv
    obtain ⟨ins', hins', htgt', hsrc', henv'⟩ := step_inv huv
    -- The label is read off the counter of the common source.
    have hsrc1 : t.src.1 = u.src.1 := by rw [hs]
    have hl : t.lbl = u.lbl := by omega
    -- Hence the same instruction ran.
    have hi : ins = ins' := by
      rw [hl, hins'] at hins
      exact (Option.some.inj hins).symm
    -- and it is injective on stores.
    have hsrc2 : t.src.2 = u.src.2 := by rw [hs]
    have htgt2 : t.tgt.2 = u.tgt.2 := by
      refine ins.run_injective ?_
      rw [← henv, hsrc2, henv', hi]
    exact Transition.ext hs hl (htb.trans hub.symm)
      (Prod.ext (by omega) htgt2)

/-- Undoing a step decreases the program counter. -/
theorem pc_lt_of_bstep {prog : Prog n} {p q : Config n} (h : BStep (lts prog) p q) :
    q.1 < p.1 := by
  obtain ⟨t, hv, hb, hs, ht⟩ := h
  subst hs; subst ht
  rw [Transition.Valid, hb] at hv
  obtain ⟨ins, _, htgt, hsrc, _⟩ := step_inv hv
  omega

/-- **Well-foundedness.**  Undoing terminates: the counter is a measure. -/
instance wellFoundedBwd (prog : Prog n) : WellFoundedBwd (lts prog) where
  wf := Subrelation.wf pc_lt_of_bstep (measure (fun c : Config n => c.1)).wf

/-- A configuration with no instruction before it has nothing left to undo. -/
theorem origin_of_no_instr {prog : Prog n} {p : Config n}
    (h : ∀ j, p.1 = j + 1 → prog[j]? = none) : Origin (lts prog) p := by
  rintro q ⟨t, hv, hb, rfl, rfl⟩
  rw [Transition.Valid, hb] at hv
  obtain ⟨ins, hins, _, hsrc, _⟩ := step_inv hv
  rw [h t.lbl hsrc] at hins
  simp at hins

/--
**Undoing is decidable.**  Read the counter: if it is `j + 1` and the program
has an instruction at `j`, that instruction ran and `Instr.undo` inverts it;
otherwise there is nothing to undo.
-/
instance bStepDec (prog : Prog n) : BStepDec (lts prog) where
  step p := by
    rcases hpc : p.1 with _ | j
    · exact .inr (origin_of_no_instr (by omega))
    · rcases hins : prog[j]? with _ | ins
      · exact .inr (origin_of_no_instr (fun j' hj' => by
          have : j' = j := by omega
          rw [this]; exact hins))
      · refine .inl ⟨(j, ins.undo p.2),
          ⟨Transition.mk p j .bwd (j, ins.undo p.2), ?_, rfl, rfl, rfl⟩⟩
        have hp : p = (j + 1, p.2) := by rw [← hpc]
        change Step prog (j, ins.undo p.2) j p
        rw [hp]
        have := Step.assign (prog := prog) hins (ins.undo p.2)
        rwa [ins.run_undo] at this

/-! ## What the machine inherits -/

/--
**Causal consistency for reversible assignment sequences.**

Nothing in the proof mentions registers: the machine discharged backward
determinism, and the theory did the rest.
-/
theorem causal_consistency_revAssign {prog : Prog n} {p q : Config n}
    {l₁ l₂ : List (Transition (Config n) Nat)}
    (h₁ : Chained (lts prog) p l₁ q) (h₂ : Chained (lts prog) p l₂ q) :
    CEq (lts prog) (NoIndep (State := Config n) (Label := Nat)) p q l₁ l₂ :=
  causal_consistency_of_bwdDeterministic h₁ h₂

/-- **However a configuration is rewound, the origin reached is the same.** -/
theorem unique_origin_revAssign {prog : Prog n} {p o₁ o₂ : Config n}
    (h₁ : Relation.ReflTransGen (BStep (lts prog)) p o₁) (ho₁ : Origin (lts prog) o₁)
    (h₂ : Relation.ReflTransGen (BStep (lts prog)) p o₂) (ho₂ : Origin (lts prog) o₂) :
    o₁ = o₂ :=
  unique_origin_of_bwdDeterministic h₁ ho₁ h₂ ho₂

/-- Every configuration can be rewound to the start of the program. -/
theorem exists_origin_revAssign {prog : Prog n} (p : Config n) :
    ∃ o, Relation.ReflTransGen (BStep (lts prog)) p o ∧ Origin (lts prog) o :=
  exists_origin_of_bwdDeterministic p

/-! ## The instance is not vacuous -/

section Examples

/-- `x += y + 1`, on two registers `x` and `y`. -/
def incX : Instr 2 :=
  ⟨0, .add (.var 1) (.const 1), ⟨show (1 : Fin 2) ≠ 0 by decide, trivial⟩⟩

/-- `y += x * 2`.  Note that this one *does* read the other register. -/
def incY : Instr 2 :=
  ⟨1, .mul (.var 0) (.const 2), ⟨show (0 : Fin 2) ≠ 1 by decide, trivial⟩⟩

/-- A two-instruction program. -/
def demo : Prog 2 := [incX, incY]

/-- The store in which both registers hold `0`. -/
def zero : Env 2 := fun _ => 0

/-- The first instruction runs, and sets `x` to `1`. -/
example : Step demo (0, zero) 0 (1, incX.run zero) := .assign rfl zero

/-- After it, `x = 1` and `y = 0`. -/
example : incX.run zero 0 = 1 ∧ incX.run zero 1 = 0 := by
  refine ⟨?_, ?_⟩ <;> simp [incX, Instr.run, zero, Expr.eval]

/-- Undoing needs no rule of its own: it is the converse of the step above. -/
example : (Transition.mk (1, incX.run zero) 0 .bwd (0, zero)).Valid (lts demo) :=
  Step.assign rfl zero

/-- The start of the program is an origin. -/
example (env : Env 2) : Origin (lts demo) (0, env) :=
  origin_of_no_instr (by omega)

/-- So is any configuration whose counter has run off the end of the program. -/
example (env : Env 2) : Origin (lts demo) (4, env) :=
  origin_of_no_instr (fun j hj => by
    have : j = 3 := by omega
    rw [this]; rfl)

end Examples

end Cslib.LTS.RevAssign
